#!/usr/bin/env bash
# publish_portal_docs.sh — Wrap sync_portal_docs.sh with the publish steps:
# commit the synced pages on a branch in the portal repo, gate on a local
# Antora build, push, and open a PR to the portal repo.
#
# Publishing is engineer-run, not CI-run (PDI-2517 decision 4): this script is
# run by a person with push access to the portal repo, never from a pipeline.
#
# Usage:
#   ci_scripts/publish_portal_docs.sh [--dry-run] [--skip-build] [PORTAL_REPO]
#
#   --dry-run    Show what would happen; no writes, pushes, or PRs.
#   --skip-build Skip the local Antora build gate (escape hatch; warns loudly).
#   PORTAL_REPO  Path to a local clone of docs-devops-getting-started
#                (required). May also be set via DOCS_PORTAL_REPO env var.
#
# Environment:
#   DOCS_PORTAL_REPO    Path to the portal clone. Resolution order:
#                       positional arg > this var > ci_scripts/.env
#                       (gitignored; see ci_scripts/.env.example).
#   DOCS_SYNC_BRANCH    Branch name in the portal repo (default: docs-sync-docker-images)

# Repo scripts avoid set -e; check return codes explicitly.
DRY_RUN=0
SKIP_BUILD=0
PORTAL_REPO_ARG=""

while test -n "${1}"; do
    case "${1}" in
        --dry-run) DRY_RUN=1 ;;
        --skip-build) SKIP_BUILD=1 ;;
        --help | -h)
            sed -n '2,26p' "${0}" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *)
            if test -z "${PORTAL_REPO_ARG}"; then
                PORTAL_REPO_ARG="${1}"
            else
                echo "Unrecognized option: ${1}"
                exit 1
            fi
            ;;
    esac
    shift
done

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Source local paths (DOCS_PORTAL_REPO etc.) if present
ENV_FILE="${REPO_ROOT}/ci_scripts/.env"
# shellcheck source=/dev/null
test -f "${ENV_FILE}" && . "${ENV_FILE}"

PORTAL_REPO="${PORTAL_REPO_ARG:-${DOCS_PORTAL_REPO:-}}"
if test -z "${PORTAL_REPO}"; then
    echo "ERROR: portal repo path is required."
    echo "       Pass it as a positional argument or set DOCS_PORTAL_REPO."
    exit 1
fi
if test ! -d "${PORTAL_REPO}/.git"; then
    echo "ERROR: not a git repo: ${PORTAL_REPO}"
    exit 1
fi
PORTAL_DIR="$(cd "${PORTAL_REPO}" && pwd)"

BRANCH="${DOCS_SYNC_BRANCH:-docs-sync-docker-images}"

echo "Portal repo: ${PORTAL_DIR}"
echo "Branch     : ${BRANCH}"
test "${DRY_RUN}" -eq 1 && echo "(dry-run: no writes, pushes, or PRs)"
echo

# --- Baseline checks ---------------------------------------------------------
PORTAL_BRANCH="$(git -C "${PORTAL_DIR}" rev-parse --abbrev-ref HEAD)"
if test "${PORTAL_BRANCH}" != "main"; then
    echo "ERROR: portal repo is on '${PORTAL_BRANCH}', expected main."
    echo "       Run ci_scripts/sync_portal_docs.sh from a clean main checkout."
    exit 1
fi

if test -n "$(git -C "${PORTAL_DIR}" status --porcelain)"; then
    echo "ERROR: portal repo has uncommitted or untracked changes:"
    git -C "${PORTAL_DIR}" status --short
    exit 1
fi

echo "==> Syncing fork main with upstream"
git -C "${PORTAL_DIR}" fetch --prune upstream
if ! git -C "${PORTAL_DIR}" merge --ff-only upstream/main; then
    echo "ERROR: main has diverged from upstream/main. Reset it:"
    echo "       git -C \"${PORTAL_DIR}\" reset --hard upstream/main"
    exit 1
fi
test "${DRY_RUN}" -eq 1 || git -C "${PORTAL_DIR}" push origin main
echo

# --- Branch + sync -----------------------------------------------------------
if git -C "${PORTAL_DIR}" show-ref --verify --quiet "refs/heads/${BRANCH}"; then
    echo "==> Reusing existing branch ${BRANCH}"
    git -C "${PORTAL_DIR}" checkout "${BRANCH}"
else
    echo "==> Creating branch ${BRANCH}"
    git -C "${PORTAL_DIR}" checkout -b "${BRANCH}" upstream/main
fi
echo

echo "==> Running sync_portal_docs.sh --regen"
SYNC_ARGS=()
test "${DRY_RUN}" -eq 1 && SYNC_ARGS+=(--dry-run)
SYNC_ARGS+=("${PORTAL_DIR}")
bash "${REPO_ROOT}/ci_scripts/sync_portal_docs.sh" "${SYNC_ARGS[@]}"
echo

if test -z "$(git -C "${PORTAL_DIR}" status --porcelain)"; then
    echo "Portal docs already current; nothing to publish."
    exit 0
fi

if test "${DRY_RUN}" -eq 1; then
    echo "(dry-run complete; no branch, commit, build, push, or PR performed)"
    exit 0
fi

# --- Commit ------------------------------------------------------------------
echo "==> Committing synced pages"
git -C "${PORTAL_DIR}" add asciidoc/modules/ROOT/pages/docker-images
git -C "${PORTAL_DIR}" commit -m "Sync generated docker-images docs from docker-builds

Regenerated by ci_scripts/deploy_docs.sh (PDI-2517) from the product
Dockerfiles and hook scripts at $(git -C "${REPO_ROOT}" rev-parse --short HEAD).

Co-Authored-By: Claude Code <noreply@anthropic.com>"
echo

# --- Local Antora build gate --------------------------------------------------
if test "${SKIP_BUILD}" -eq 1; then
    echo "WARN: --skip-build set; skipping the local Antora build gate." >&2
    echo "      A local build failure guarantees a publish-pipeline failure." >&2
else
    if test ! -d "${PORTAL_DIR}/node_modules"; then
        echo "==> Installing portal node dependencies"
        npm --prefix "${PORTAL_DIR}" install
    fi
    echo "==> Running local preview build"
    (
        cd "${PORTAL_DIR}" &&
            npx pingdocs build playbook-preview.yml
    ) || {
        echo "ERROR: Antora build failed. Fix the pages and rerun:"
        echo "       ci_scripts/publish_portal_docs.sh ${PORTAL_DIR}"
        exit 1
    }
    echo "Preview built: ${PORTAL_DIR}/target/build/site/index.html"
fi
echo

# --- Push + PR ----------------------------------------------------------------
echo "==> Pushing ${BRANCH}"
git -C "${PORTAL_DIR}" push -u origin "${BRANCH}"

# The portal remote is a fork; gh must address the head branch as
# "<fork-user>:<branch>" or it looks for the branch on upstream and fails.
GH_FORK_USER=$(gh api user --jq .login)

EXISTING=$(gh pr list --repo ping-rocks/docs-devops-getting-started \
    --head "${GH_FORK_USER}:${BRANCH}" --state open \
    --json number,url --jq '.[0].url // empty')

if test -n "${EXISTING}"; then
    echo "PR already open: ${EXISTING}"
else
    PR_URL=$(gh pr create --repo ping-rocks/docs-devops-getting-started \
        --base main --head "${GH_FORK_USER}:${BRANCH}" \
        --title "Sync generated docker-images docs from docker-builds" \
        --body "Automated sync from docker-builds ci_scripts/deploy_docs.sh (PDI-2517).

Regenerated from the product Dockerfiles and hook scripts; see the
commit message for the source revision.

🤖 Generated with [Claude Code](https://claude.com/claude-code)")
    echo "PR: ${PR_URL}"
fi
