#!/usr/bin/env sh
#
# Ping Identity DevOps - Docker Build Hooks
#
test "${VERBOSE}" = "true" && set -x

# shellcheck source=../../../../pingcommon/opt/staging/hooks/pingcommon.lib.sh
. "${HOOKS_DIR}/pingcommon.lib.sh"

echo "Configuring tools.properties"
TOOLS_PROPERTIES_FILE="${SERVER_ROOT_DIR}"/config/tools.properties

mv "${TOOLS_PROPERTIES_FILE}" "${TOOLS_PROPERTIES_FILE}.orig"

echo "
#
# Generated by PingIdentity DevOps ${0}
#
hostname=localhost
port=${LDAPS_PORT}
useSSL=true
useStartTLS=false
trustAll=true
bindDN=${ROOT_USER_DN}
bindPasswordFile=${ROOT_USER_PASSWORD_FILE}
adminUID=${ADMIN_USER_NAME}
adminPasswordFile=${ADMIN_USER_PASSWORD_FILE}
suppressPropertiesFileComment=true

ldapsearch.dontWrap=true
" > "${TOOLS_PROPERTIES_FILE}"
