version: "2.4"

services:
  sut:
    image: ${REGISTRY}/pingdatagovernance:8.0.0.1-alpine-az11-${GIT_TAG}
    environment:
      - PING_IDENTITY_DEVOPS_USER=${PING_IDENTITY_DEVOPS_USER}
      - PING_IDENTITY_DEVOPS_KEY=${PING_IDENTITY_DEVOPS_KEY}
      - PING_IDENTITY_ACCEPT_EULA=YES
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=getting-started/pingdatagovernance-8.0.0.0
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    mem_limit: ${KUBERNETES_MEMORY_LIMIT:-4000000000}b
    memswap_limit: ${KUBERNETES_MEMORY_LIMIT:-4000000000}b
    oom_kill_disable: true
    mem_swappiness: 0
    tmpfs: /run/secrets
    command: start-server /opt/wait-for localhost:443 -t 300 -- /opt/liveness.sh
