version: "2.4"

services:
  pingdirectory:
    image: ${REGISTRY}/pingdirectory:${PINGDIRECTORY_LATEST}-alpine-az11-${GIT_TAG}
    #  for local testing
    # image: pingidentity/pingdirectory:8.0.0.1-alpine-az11-re-pa-cluster-d4eb
    environment:
      - SERVER_PROFILE_PATH=baseline/pingdirectory
      - MAX_HEAP_SIZE=768m
    env_file:
      # Property file below provides common envrionment variables for all integration_tests.
      # run_integration.sh creates /tmp/integration_tests.properties at runtime.
      - /tmp/integration_tests.properties
    ports:
      - "1443:443"
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    mem_limit: 1g
    memswap_limit: 1g
    mem_swappiness: 0
    ################################################
    # /run/secrets - tmpfs
    ################################################
    volumes:
      - type: tmpfs
        target: /run/secrets
        tmpfs:
          size: 16m

  pingdatagovernance:
    image: ${REGISTRY}/pingdatagovernance:${PINGDATAGOVERNANCE_LATEST}-alpine-az11-${GIT_TAG}
    # for local testing
    # image: pingidentity/pingdatagovernance:8.0.0.1-alpine-az11-re-pa-cluster-d4eb
    command: wait-for pingdirectory:389 -t 900 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_PATH=baseline/pingdatagovernance
    env_file:
      - /tmp/integration_tests.properties
    ports:
      - "7443:443"
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    mem_limit: 1g
    memswap_limit: 1g
    mem_swappiness: 0
    ################################################
    # /run/secrets - tmpfs
    ################################################
    volumes:
      - type: tmpfs
        target: /run/secrets
        tmpfs:
          size: 16m
    depends_on: ["pingdirectory"]

  sut:
    image: postman/newman
    entrypoint: ["/usr/bin/env"]
    command: sh -c "/tmp/wait-for pingdatagovernance:443 -t 900 -- newman run /tmp/collection.json --insecure --ignore-redirects"
    volumes:
      - ./pdg-pd.postman_collection.json:/tmp/collection.json
      - ./wait-for:/tmp/wait-for
    depends_on: ["pingdatagovernance"]